image: node:9.5.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install -g aerobatic-cli gulp-cli
            - npm install
            - gulp build --no-cache --throw-errors
            - aero deploy
  custom:
    build:
      - step:
          caches:
            - node
          script:
            - npm install -g aerobatic-cli gulp-cli
            - npm install
            - gulp build --no-cache --throw-errors
            - aero deploy
    lint:
      - step:
          caches:
            - node
          script:
            - npm install -g gulp-cli
            - npm install
            - gulp lint --no-notify
